name: A-windows-2

on: 
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-2022
    timeout-minutes: 9999
    
    steps:
    - name: Setting the environment up.
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
        VNC_USER_PASSWORD: ${{ secrets.VNC_USER_PASSWORD }}
        VNC_PASSWORD: ${{ secrets.VNC_PASSWORD }}
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
    - run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 5
    - run: Set-LocalUser -Name "$VNC_USER_PASSWORD" -Password (ConvertTo-SecureString -AsPlainText "$VNC_PASSWORD" -Force)
    - name: Download
      run: |
       Invoke-WebRequest https://download.anydesk.com/AnyDesk.exe -OutFile AnyDesk.exe
       Invoke-WebRequest https://raw.githubusercontent.com/tchaluckla/painthyste/master/aidi.bat -OutFile aidi.bat
    - name: Install
      run: .\anydesk.exe --install "C:\Program Files (x86)\AnyDesk" --start-with-win
    - name: Sleep
      run: sleep 5
    - name: Show ID
      run: .\aidi.bat
    - name: Loop
      run: sleep 99999
